<%@ Page Title="Pagos" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="rPagos.aspx.cs" Inherits="AnalisisUI.Registros.rPagos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
     <div class="panel panel-primary">
        <div class="panel-body">
              <div class="form-horizontal col-md-14" role="form">
                   <%--ID & Fecha--%>
                <div class="form-group row">
                    <label for="ID" class="col-sm-1 col-form-label">ID</label>
                    <div class="col-md-1 col-sm-2 col-xs-4">
                        <asp:TextBox type="number" ID="IDTextBox" runat="server" min=0 class="form-control input-sm"></asp:TextBox>
                    </div>
                    <div class="col-md-3 col-sm-2 col-xs-4">
                         <asp:LinkButton ID="BuscarButton" CssClass="btn btn-dark btn-block btn-md" CausesValidation="false" runat="server" Text="Buscar" OnClick="BuscarButton_Click"></asp:LinkButton>
                    </div>    
                    
                </div>
                   <%--DETALLE--%>
                  <div class="form-group row">
                    <label for="Id" class="col-sm-1 col-form-label">AnalisisId</label>
                    <div class="col-md-4">
                        <asp:DropDownList runat="server" ID="AnalisisDropDown" CssClass="form-control input-sm" AutoPostBack="true"></asp:DropDownList>
                    </div>
                       <label for="MontoPagado" class="col-xs-2 col-form-label">Monto Pagar</label>
                      <div class="col-md-2">
                        <asp:TextBox ID="MontoPagadoTextBox" runat="server" Class="form-control input-sm"></asp:TextBox>
                      </div>
                      <div class="col-xs-2">
                        <asp:LinkButton runat="server" ID="AgregarGrid" ValidationGroup="Analisis" CssClass="btn btn-outline-info btn-md" Text="Agregar" OnClick="AgregarGrid_Click"></asp:LinkButton>
                    </div>
                </div>
                   <%--GRID--%>
                <asp:GridView ID="Grid" CssClass=" col-md-offset-4 col-sm-offset-4" runat="server" DataKeyNames="PagosDetalleId" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="false" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333" GridLines="None" Width="767px" AutoGenerateColumns="false" OnPageIndexChanging="Grid_PageIndexChanging" OnRowDeleting="Grid_RowDeleting" >                         
                    <Columns>
                        <asp:BoundField DataField="AnalisisId" HeaderText="AnalisisId" /><asp:BoundField />
                        <asp:BoundField DataField="MontoAnalisis" HeaderText="BalancePagar" /><asp:BoundField />
                        <asp:BoundField DataField="MontoPagado" HeaderText="MontoPagado" /><asp:BoundField />

                    </Columns>     
                    <EmptyDataTemplate><div style="text-align:center">No hay datos en el Grid.</div></EmptyDataTemplate>
                         <AlternatingRowStyle BackColor="White" />

                            <EditRowStyle BackColor="#2461BF" />
                            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#EFF3FB" />
                            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F5F7FB" />
                            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                            <SortedDescendingCellStyle BackColor="#E9EBEF" />
                            <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
                  <br /><br />
                  <div class ="form-group row">
                    <label for="Pagado" class="col-sm-1 col-form-label">Pagado</label>
                    <div class="col-sm-4">
                        <asp:TextBox runat="server" ID="PagadoTextBox" CssClass="form-control input-sm" ReadOnly="true"></asp:TextBox>
                    </div>
               </div>
        </div>
             <asp:Label ID="Mensaje" runat="server" CssClass="col-form-label-lg" Text=""></asp:Label>
     </div>
         <br />
           <div class="panel-footer">
            <div class="text-center">
                <div class="form-group" style="display: inline-block">

                    <asp:Button Text="Nuevo" class="btn btn-warning btn-sm" CausesValidation="false" style="color:#fff" runat="server" ID="NuevoButton" OnClick="NuevoButton_Click"  />
                    <asp:Button Text="Guardar" class="btn btn-success btn-sm" runat="server" ID="GuardarButton" OnClick="GuardarButton_Click"/>
                    <asp:Button Text="Eliminar" class="btn btn-danger btn-sm" CausesValidation="false" runat="server" ID="EliminarButton" OnClick="EliminarButton_Click" />

                </div>
            </div>

        </div>
    </div>
</asp:Content>
